graph [
 directed 1
 node [ id 2 label "STATE_0" ]
 node [ id 3 label "STATE_1" ]
 node [ id 4 label "STATE_2" ]
 node [ id 5 label "STATE_3" ]
 node [ id 6 label "STATE_4" ]
 node [ id 7 label "STATE_5" ]
 node [ id 8 label "STATE_6" ]
 node [ id 9 label "STATE_7" ]
 node [ id 1 label "STATE_IDLE" ]
 node [ id 10 label "STATE_READING" ]
 edge [ source 2 target 3 ] 
 edge [ source 3 target 4 ] 
 edge [ source 4 target 5 ] 
 edge [ source 5 target 6 ] 
 edge [ source 6 target 7 ] 
 edge [ source 7 target 8 ] 
 edge [ source 8 target 9 ] 
 edge [ source 9 target 2 ] 
 edge [ source 9 target 1 ] 
 edge [ source 1 target 2 ] 
 edge [ source 1 target 1 ] 
 edge [ source 1 target 10 ] 
 edge [ source 10 target 1 ] 
 edge [ source 10 target 10 ] 
]
