graph [
 directed 1
 node [ id 2 label "STATE_END_RUN" ]
 node [ id 1 label "STATE_IDLE" ]
 node [ id 3 label "STATE_LEVEL" ]
 node [ id 4 label "STATE_RUN" ]
 node [ id 5 label "STATE_WAIT_EOB" ]
 edge [ source 2 target 2 ] 
 edge [ source 2 target 1 ] 
 edge [ source 1 target 2 ] 
 edge [ source 1 target 1 ] 
 edge [ source 1 target 3 ] 
 edge [ source 1 target 4 ] 
 edge [ source 3 target 1 ] 
 edge [ source 3 target 5 ] 
 edge [ source 4 target 3 ] 
 edge [ source 4 target 4 ] 
 edge [ source 4 target 5 ] 
 edge [ source 5 target 1 ] 
 edge [ source 5 target 5 ] 
]
