graph [
 directed 1
 node [ id 51 label "STATE_BLOCK" ]
 node [ id 50 label "STATE_CODED_BLOCK_PATTERN" ]
 node [ id 55 label "STATE_CODED_BLOCK_PATTERN_1" ]
 node [ id 56 label "STATE_CODED_BLOCK_PATTERN_2" ]
 node [ id 59 label "STATE_DCT_DC_CHROMI_SIZE" ]
 node [ id 63 label "STATE_DCT_DC_DIFF" ]
 node [ id 64 label "STATE_DCT_DC_DIFF_0" ]
 node [ id 58 label "STATE_DCT_DC_LUMI_SIZE" ]
 node [ id 62 label "STATE_DCT_ERROR" ]
 node [ id 68 label "STATE_DCT_ESCAPE_B14" ]
 node [ id 67 label "STATE_DCT_ESCAPE_B15" ]
 node [ id 60 label "STATE_DCT_NON_INTRA_FIRST" ]
 node [ id 66 label "STATE_DCT_SUBS_B14" ]
 node [ id 65 label "STATE_DCT_SUBS_B15" ]
 node [ id 43 label "STATE_DCT_TYPE" ]
 node [ id 40 label "STATE_DELAY_EMPTY_BLOCK" ]
 node [ id 41 label "STATE_EMIT_EMPTY_BLOCK" ]
 node [ id 21 label "STATE_ERROR" graphics [ type "ellipse" ] ]
 node [ id 5 label "STATE_EXTENSION_START_CODE" graphics [ type "ellipse" ] ]
 node [ id 7 label "STATE_GROUP_HEADER" ]
 node [ id 31 label "STATE_GROUP_HEADER0" graphics [ type "ellipse" ] ]
 node [ id 27 label "STATE_LD_CHROMA_INTRA_QUANT1" graphics [ type "ellipse" ] ]
 node [ id 28 label "STATE_LD_CHROMA_NON_INTRA_QUANT1" graphics [ type "ellipse" ] ]
 node [ id 17 label "STATE_LD_INTRA_QUANT0" graphics [ type "ellipse" ] ]
 node [ id 25 label "STATE_LD_INTRA_QUANT1" graphics [ type "ellipse" ] ]
 node [ id 18 label "STATE_LD_NON_INTRA_QUANT0" graphics [ type "ellipse" ] ]
 node [ id 26 label "STATE_LD_NON_INTRA_QUANT1" graphics [ type "ellipse" ] ]
 node [ id 44 label "STATE_MACROBLOCK_QUANT" ]
 node [ id 39 label "STATE_MACROBLOCK_SKIP" ]
 node [ id 38 label "STATE_MACROBLOCK_TYPE" ]
 node [ id 49 label "STATE_MARKER_BIT_0" ]
 node [ id 48 label "STATE_MOTION_CODE" ]
 node [ id 53 label "STATE_MOTION_DMVECTOR" ]
 node [ id 46 label "STATE_MOTION_PIPELINE_FLUSH" ]
 node [ id 54 label "STATE_MOTION_PREDICT" ]
 node [ id 52 label "STATE_MOTION_RESIDUAL" ]
 node [ id 42 label "STATE_MOTION_TYPE" ]
 node [ id 47 label "STATE_MOTION_VERT_FLD_SEL" ]
 node [ id 57 label "STATE_NEXT_BLOCK" graphics [ type "ellipse" ] ]
 node [ id 36 label "STATE_NEXT_MACROBLOCK" ]
 node [ id 45 label "STATE_NEXT_MOTION_VECTOR" ]
 node [ id 1 label "STATE_NEXT_START_CODE" graphics [ type "ellipse" ] ]
 node [ id 61 label "STATE_NON_CODED_BLOCK" ]
 node [ id 12 label "STATE_PICTURE_CODING_EXT" ]
 node [ id 29 label "STATE_PICTURE_CODING_EXT0" graphics [ type "ellipse" ] ]
 node [ id 30 label "STATE_PICTURE_CODING_EXT1" graphics [ type "ellipse" ] ]
 node [ id 3 label "STATE_PICTURE_HEADER" ]
 node [ id 32 label "STATE_PICTURE_HEADER0" graphics [ type "ellipse" ] ]
 node [ id 33 label "STATE_PICTURE_HEADER1" graphics [ type "ellipse" ] ]
 node [ id 34 label "STATE_PICTURE_HEADER2" graphics [ type "ellipse" ] ]
 node [ id 11 label "STATE_QUANT_MATRIX_EXT" graphics [ type "ellipse" ] ]
 node [ id 10 label "STATE_SEQUENCE_DISPLAY_EXT" ]
 node [ id 22 label "STATE_SEQUENCE_DISPLAY_EXT0" ]
 node [ id 23 label "STATE_SEQUENCE_DISPLAY_EXT1" graphics [ type "ellipse" ] ]
 node [ id 24 label "STATE_SEQUENCE_DISPLAY_EXT2" graphics [ type "ellipse" ] ]
 node [ id 6 label "STATE_SEQUENCE_END" graphics [ type "ellipse" ] ]
 node [ id 9 label "STATE_SEQUENCE_EXT" ]
 node [ id 19 label "STATE_SEQUENCE_EXT0" ]
 node [ id 20 label "STATE_SEQUENCE_EXT1" graphics [ type "ellipse" ] ]
 node [ id 4 label "STATE_SEQUENCE_HEADER" ]
 node [ id 13 label "STATE_SEQUENCE_HEADER0" ]
 node [ id 14 label "STATE_SEQUENCE_HEADER1" ]
 node [ id 15 label "STATE_SEQUENCE_HEADER2" ]
 node [ id 16 label "STATE_SEQUENCE_HEADER3" graphics [ type "ellipse" ] ]
 node [ id 8 label "STATE_SLICE" ]
 node [ id 35 label "STATE_SLICE_EXTENSION" ]
 node [ id 37 label "STATE_SLICE_EXTRA_INFORMATION" ]
 node [ id 2 label "STATE_START_CODE" graphics [ type "ellipse" ] ]
 edge [ source 51 target 57 ] 
 edge [ source 50 target 51 ] 
 edge [ source 50 target 55 ] 
 edge [ source 50 target 56 ] 
 edge [ source 55 target 51 ] 
 edge [ source 56 target 51 ] 
 edge [ source 59 target 63 ] 
 edge [ source 59 target 62 ] 
 edge [ source 63 target 64 ] 
 edge [ source 64 target 66 ] 
 edge [ source 64 target 65 ] 
 edge [ source 58 target 63 ] 
 edge [ source 58 target 62 ] 
 edge [ source 62 target 61 ] 
 edge [ source 68 target 66 ] 
 edge [ source 67 target 65 ] 
 edge [ source 60 target 62 ] 
 edge [ source 60 target 68 ] 
 edge [ source 60 target 66 ] 
 edge [ source 66 target 62 ] 
 edge [ source 66 target 68 ] 
 edge [ source 66 target 66 ] 
 edge [ source 66 target 57 ] 
 edge [ source 65 target 62 ] 
 edge [ source 65 target 67 ] 
 edge [ source 65 target 65 ] 
 edge [ source 65 target 57 ] 
 edge [ source 43 target 44 ] 
 edge [ source 40 target 41 ] 
 edge [ source 41 target 41 ] 
 edge [ source 41 target 39 ] 
 edge [ source 41 target 38 ] 
 edge [ source 21 target 1 ] 
 edge [ source 5 target 12 ] 
 edge [ source 5 target 11 ] 
 edge [ source 5 target 10 ] 
 edge [ source 5 target 9 ] 
 edge [ source 7 target 31 ] 
 edge [ source 27 target 27 ] 
 edge [ source 27 target 28 ] 
 edge [ source 28 target 28 ] 
 edge [ source 17 target 17 ] 
 edge [ source 17 target 18 ] 
 edge [ source 25 target 27 ] 
 edge [ source 25 target 28 ] 
 edge [ source 25 target 25 ] 
 edge [ source 25 target 26 ] 
 edge [ source 18 target 18 ] 
 edge [ source 26 target 27 ] 
 edge [ source 26 target 28 ] 
 edge [ source 26 target 26 ] 
 edge [ source 44 target 45 ] 
 edge [ source 39 target 40 ] 
 edge [ source 39 target 38 ] 
 edge [ source 38 target 42 ] 
 edge [ source 49 target 51 ] 
 edge [ source 49 target 50 ] 
 edge [ source 48 target 53 ] 
 edge [ source 48 target 54 ] 
 edge [ source 48 target 52 ] 
 edge [ source 53 target 54 ] 
 edge [ source 46 target 51 ] 
 edge [ source 46 target 50 ] 
 edge [ source 46 target 49 ] 
 edge [ source 46 target 46 ] 
 edge [ source 54 target 45 ] 
 edge [ source 52 target 53 ] 
 edge [ source 52 target 54 ] 
 edge [ source 42 target 43 ] 
 edge [ source 42 target 44 ] 
 edge [ source 47 target 48 ] 
 edge [ source 57 target 59 ] 
 edge [ source 57 target 58 ] 
 edge [ source 57 target 60 ] 
 edge [ source 57 target 57 ] 
 edge [ source 57 target 36 ] 
 edge [ source 57 target 61 ] 
 edge [ source 36 target 39 ] 
 edge [ source 36 target 38 ] 
 edge [ source 36 target 36 ] 
 edge [ source 45 target 48 ] 
 edge [ source 45 target 46 ] 
 edge [ source 45 target 47 ] 
 edge [ source 45 target 45 ] 
 edge [ source 1 target 2 ] 
 edge [ source 61 target 57 ] 
 edge [ source 12 target 29 ] 
 edge [ source 29 target 30 ] 
 edge [ source 3 target 32 ] 
 edge [ source 32 target 33 ] 
 edge [ source 33 target 34 ] 
 edge [ source 11 target 27 ] 
 edge [ source 11 target 28 ] 
 edge [ source 11 target 25 ] 
 edge [ source 11 target 26 ] 
 edge [ source 10 target 22 ] 
 edge [ source 10 target 23 ] 
 edge [ source 22 target 23 ] 
 edge [ source 23 target 24 ] 
 edge [ source 9 target 19 ] 
 edge [ source 19 target 20 ] 
 edge [ source 4 target 13 ] 
 edge [ source 13 target 14 ] 
 edge [ source 14 target 15 ] 
 edge [ source 15 target 16 ] 
 edge [ source 16 target 17 ] 
 edge [ source 16 target 18 ] 
 edge [ source 8 target 36 ] 
 edge [ source 8 target 35 ] 
 edge [ source 35 target 36 ] 
 edge [ source 35 target 37 ] 
 edge [ source 37 target 36 ] 
 edge [ source 37 target 37 ] 
 edge [ source 2 target 5 ] 
 edge [ source 2 target 7 ] 
 edge [ source 2 target 3 ] 
 edge [ source 2 target 6 ] 
 edge [ source 2 target 4 ] 
 edge [ source 2 target 8 ] 
]
